'use strict';
LB.specials=[['Flying side kick','kick','air'],['Flying knee','knee','air'],['Spinning heel kick','kick','spin'],['Cartwheel kick','kick','cartwheel'],['Superman punch','punch','air'],['Dropkick','kick','dive'],['Backdoor bastard','punch','vault'],['Wall rebound strike','kick','wall'],['Running clothesline','punch','charge'],['Tornado kick','kick','spin'],['Shoulder charge','body','charge'],['Sliding tackle','kick','slide'],['Knee-slide uppercut','punch','slide'],['Backflip escape kick','kick','flip'],['Diving elbow','punch','dive'],['Head-scissors takedown','grapple','scissors'],['Swinging neckbreaker','grapple','neckbreaker'],['Fireman carry','grapple','carry'],['Belly-to-belly throw','grapple','belly'],['Suplex','grapple','suplex'],['Human-javelin throw','grapple','javelin'],['Knee slam','grapple','knee'],['Ground slam','grapple','slam'],['Airplane spin','grapple','airplane'],['Crowd-surf throw','grapple','crowd']].map((s,id)=>({id,name:s[0],kind:s[1],motion:s[2]}));
LB.moves={punch:['Jab','Cross','Hook','Body hook','Uppercut','Overhand punch','Backfist','Superman punch','Counterpunch','Multi-punch combination'],kick:['Front kick','Side kick','Roundhouse','Low kick','Head kick','Spinning heel kick','Flying side kick','Flying knee','Cartwheel kick','Dropkick']};
LB.bodySpecs=[{w:24,hip:21,torso:67,leg:103,arm:88,head:1.08},{w:25,hip:22,torso:88,leg:128,arm:107,head:.9},{w:34,hip:29,torso:78,leg:107,arm:92,head:1},{w:40,hip:26,torso:78,leg:112,arm:95,head:.96},{w:34,hip:44,torso:69,leg:98,arm:86,head:1.02},{w:54,hip:29,torso:87,leg:94,arm:98,head:.96},{w:47,hip:43,torso:74,leg:92,arm:85,head:1.04},{w:54,hip:29,torso:84,leg:108,arm:104,head:.94},{w:49,hip:45,torso:64,leg:86,arm:81,head:1.06},{w:59,hip:46,torso:91,leg:95,arm:96,head:1.06}];
LB.Animation={ik(a,b,l1,l2,bend=1){const dx=b.x-a.x,dy=b.y-a.y,d=LB.clamp(Math.hypot(dx,dy),.01,l1+l2-.02),ang=Math.atan2(dy,dx),cos=LB.clamp((l1*l1+d*d-l2*l2)/(2*l1*d),-1,1),q=ang+bend*Math.acos(cos);return{x:a.x+Math.cos(q)*l1,y:a.y+Math.sin(q)*l1}},pose(f,t){const a=f.appearance,b=LB.bodySpecs[a.body],state=f.state||'idle',p={pelvis:{x:0,y:-b.leg},torso:Math.sin(t*1.7)*.012,head:Math.sin(t*1.3)*.028,frontHand:{x:b.w+35,y:-b.leg-b.torso+39},rearHand:{x:-b.w+8,y:-b.leg-b.torso+32},frontFoot:{x:28,y:0},rearFoot:{x:-27,y:0},rotation:0,y:0,face:'focused',hand:'fist',weaponAngle:.2,headScale:1};let u=f.action?LB.clamp(f.action.time/f.action.duration,0,1):0,impact=f.action?f.action.impact/f.action.duration:.45;let strike=u<impact?Math.pow(u/impact,3):Math.max(0,1-(u-impact)/(1-impact));const wind=Math.sin(Math.min(1,u/impact)*Math.PI);
if(state==='idle'){p.face='smug';p.pelvis.y+=Math.sin(t*3)*1.6;p.frontHand.y+=Math.sin(t*2)*2;p.rearHand.x+=Math.sin(t*2+.6)*2;p.hand='relaxed'}
if(state==='walk'||state==='run'){const phase=f.stride||0,amp=state==='run'?36:24,dir=f.moveDir||1;for(const [key,offset]of [['frontFoot',0],['rearFoot',Math.PI]]){let q=(phase+offset)%(Math.PI*2);p[key]={x:Math.cos(q)*amp*dir,y:-Math.max(0,Math.sin(q))*26}}p.pelvis.y-=Math.abs(Math.sin(phase))*5;p.torso=.09*dir;p.frontHand.x+=Math.cos(phase+Math.PI)*16;p.frontHand.y+=Math.sin(phase)*15;p.rearHand.x+=Math.cos(phase)*16;p.head=-.06*dir}
if(['punch','weapon','combo','special','kick','throw'].includes(state)){const act=f.action||{},kind=act.kind||state,variant=act.variant||0;let targetY=act.target==='head'?-b.leg-b.torso-33:act.target==='limb'?-50:-b.leg-b.torso*.55;let targetX=(b.w+b.arm-4)*(1+LB.abilityValue(f,'reach')); if(kind==='punch'||kind==='weapon'||kind==='combo'||kind==='throw'){p.torso=-.15*wind+.12*strike;p.frontHand={x:LB.lerp(b.w+17-wind*40,targetX,strike),y:LB.lerp(-b.leg-b.torso+42,targetY,strike)};if(variant%5===4)p.frontHand.y+=Math.sin(u*Math.PI*2)*26;p.rearHand.x+=18*strike;p.frontFoot.x+=10*strike;p.weaponAngle=LB.lerp(-1.5,1.7,strike);p.head=-.05;p.face=u<impact?'angry':'focused'}if(kind==='kick'||kind==='knee'){p.torso=-.28*strike;p.frontFoot={x:LB.lerp(15,130,strike),y:LB.lerp(-30*wind,targetY+15,strike)};p.frontHand={x:8,y:-b.leg-b.torso+30};p.rearHand={x:-b.w-35,y:-b.leg-b.torso+12};p.pelvis.y-=8*strike;p.face='angry'}if(state==='throw'){p.frontHand.x=LB.lerp(-35,targetX,strike);p.frontHand.y=LB.lerp(-b.leg-b.torso-50,-b.leg-b.torso+5,strike);p.weaponAngle=1.7*strike-1}
if(state==='special'){const motion=act.motion;const air=Math.sin(Math.PI*u);if(['air','vault','wall','dive','flip','cartwheel','spin'].includes(motion))p.y=-air*(motion==='vault'?125:motion==='dive'?85:65);if(['spin','cartwheel','flip'].includes(motion))p.rotation=motion==='spin'?Math.sin(u*Math.PI*2)*.5:(motion==='flip'?-1:1)*Math.sin(u*Math.PI)*1.1;if(motion==='dive')p.rotation=.9*air;if(motion==='slide'){p.pelvis.y+=42*air;p.rearFoot.x=-58;p.torso=-.4*air}if(motion==='charge'){p.torso=.35*air;p.frontHand.y=-b.leg-b.torso+45}if(motion==='vault')p.rearFoot.y=-50*air;p.face=air>.5?'shocked':'angry'}
}
if(state==='block'){p.frontHand={x:b.w+18,y:-b.leg-b.torso-8+(f.guard==='low'?80:f.guard==='middle'?40:0)};p.rearHand={x:8,y:p.frontHand.y+12};p.hand='block';p.face='angry';p.torso=-.08}
if(['headSway','bodySway','stepBack'].includes(state)){let s=Math.sin(u*Math.PI);p.face='smug';if(state==='headSway'){p.head=-.28*s;p.torso=-.08*s}else if(state==='bodySway'){p.torso=-.5*s;p.pelvis.x=-8*s;p.frontHand.y+=25*s}else{p.y=-45*s;p.pelvis.x=-18*s;p.frontFoot.y=-25*s;p.rearFoot.y=-18*s;p.torso=-.25*s;p.hand='open'}}
if(['hurt','stunned','stumble'].includes(state)){const q=f.hitTimer||.2;p.torso=-.25*Math.min(1,q*3);p.head=-.3;p.frontHand.x-=25;p.frontHand.y+=30;p.face=state==='stunned'?'dizzy':'hurt';p.rearFoot.x-=20;p.hand='open'}
if(state==='grapple'){p.frontHand={x:b.w+60,y:-b.leg-b.torso+10};p.rearHand={x:b.w+42,y:-b.leg-b.torso+44};p.hand='grapple';p.torso=.12;p.face='angry';if(u>.28&&u<.68){p.frontHand.y-=55;p.rearHand.y-=40;p.pelvis.y-=12;p.torso=-.2}if(u>.68)p.torso=.45*Math.sin((u-.68)/.32*Math.PI)}
if(['grappled','lifted','carried','thrown','slammed'].includes(state)){p.frontHand={x:b.w+33,y:-b.leg-b.torso-15};p.rearHand={x:-b.w-30,y:-b.leg-b.torso-8};p.frontFoot={x:45,y:-25};p.rearFoot={x:-45,y:-35};p.hand='falling';p.face='scared';p.head=.2*Math.sin(t*9)}
if(['fall','knockdown','defeat','unconscious'].includes(state)){let fall=f.fallProgress??1;p.rotation=-Math.min(1,fall)*1.5;p.y=LB.lerp(0,-20,fall);p.frontHand={x:b.w+38,y:-b.leg-b.torso+58};p.rearHand={x:-b.w-22,y:-b.leg-b.torso+60};p.frontFoot.y=-12;p.rearFoot.y=-25;p.face=fall>.8?'unconscious':'shocked';p.hand='limp'}
if(state==='getup'){let q=1-u;p.rotation=-1.4*q;p.y=-20*q;p.pelvis.y+=30*Math.sin(u*Math.PI);p.face='exhausted'}
if(state==='victory'){p.frontHand={x:b.w+16,y:-b.leg-b.torso-75};p.rearHand={x:-b.w-25,y:-b.leg-b.torso-20};p.hand='victory';p.face='victorious';p.pelvis.y+=Math.sin(t*5)*3;p.torso=Math.sin(t*3)*.07}
if(state==='pickup'){p.torso=.65*Math.sin(u*Math.PI);p.pelvis.y+=25*Math.sin(u*Math.PI);p.frontHand.y=LB.lerp(-100,-8,Math.sin(u*Math.PI));p.frontHand.x=60;p.face='focused';p.hand='open'}
if(f.stamina<18&&state==='idle')p.face='exhausted';p.face=f.expression||p.face;return p}};
