'use strict';
LB.Combat={
start(f,kind,forced={}){if(f.hp<=0||['grappled','lifted','carried','thrown'].includes(f.state))return false;const weapon=LB.weaponById(f.weapon),speed=f.attackSpeed;let duration=kind==='weapon'?.70/(weapon?.speed||1):kind==='kick'?.58:kind==='grapple'?1.45:kind==='special'?1.0:kind==='combo'?.36:kind==='throw'?.65:.45;duration/=speed;let spec=forced.special??(kind==='special'?LB.pick(LB.specials):null);if(spec?.kind==='grapple')kind='grapple';let target=forced.target||LB.pick(['head','body','body','limb']);if(spec?.kind==='grapple')target='body';const cost=kind==='special'?26:kind==='grapple'?24:kind==='kick'?16:kind==='weapon'?14:kind==='combo'?11:9;if(f.stamina<cost&&!forced.lab){f.state='block';f.guard='middle';f.cooldown=.32;return false}f.stamina=Math.max(0,f.stamina-cost);f.state=kind;f.action={kind:spec?spec.kind:kind,time:0,duration,impact:duration*(kind==='grapple'?.76:.44),done:false,target,variant:forced.variant??Math.floor(Math.random()*10),motion:spec?.motion,special:spec,name:spec?.name||LB.pick(LB.moves[kind]||[kind]),lab:forced.lab,rare:forced.rare,finisher:forced.finisher,counter:forced.counter};f.cooldown=.2;f.expression=null;if(kind==='special')f.stats.specials++;if(kind==='grapple'){f.action.duration=1.45/speed;f.action.impact=f.action.duration*.76;f.action.kind='grapple';f.action.motion=spec?.motion||LB.pick(['suplex','slam','javelin','carry','airplane','crowd']);LB.Dialogue.say(f,'grapple',true)}if(kind==='combo')f.action.comboLeft=forced.comboLeft??2;return true},
dodge(f,kind){const cost=kind==='stepBack'?26:kind==='bodySway'?17:9;if(f.stamina<cost)return;f.stamina-=cost;f.state=kind;f.action={kind,time:0,duration:.48,impact:2};f.cooldown=.16;f.stats.dodges++;f.gainPopularity(kind==='stepBack'?4:7);if(Math.random()<.28)LB.Dialogue.say(f,'dodge',true)},
update(f,dt){const enemy=f.opponent;if(!enemy)return;f.stamina=Math.min(100,f.stamina+dt*(f.state==='block'?29*(1+LB.abilityValue(f,'rest')):22)*(1+LB.abilityValue(f,'stamina')));f.comboTimer-=dt;if(f.comboTimer<=0)f.combo=0;if(f.hp<=0)return;if(['grappled','lifted','carried','thrown'].includes(f.state))return;if(f.hitTimer>0){f.hitTimer-=dt;if(f.hitTimer<=0){if(f.state==='knockdown'){f.state='getup';f.action={kind:'getup',time:0,duration:.48,impact:2}}else{f.state='idle';f.cooldown=.12}}return}if(f.action){const act=f.action;act.time+=dt;let u=act.time/act.duration;if(f.state==='stepBack')f.x-=f.facing*135*dt;if(f.state==='grapple'){this.grapple(f,enemy,act,u,dt)}else if(!act.done&&act.time>=act.impact){act.done=true;if(f.state==='throw')LB.Physics.throwWeapon(f);else if(['punch','kick','weapon','special','combo'].includes(f.state))this.contact(f,enemy,act)}if(act.time>=act.duration&&f.action===act){f.action=null;f.state='idle';f.cooldown=LB.rand(.055,.16)/f.attackSpeed;if(act.comboLeft>0&&enemy.hp>0&&f.stamina>15){this.start(f,'combo',{comboLeft:act.comboLeft-1,target:act.target==='head'?'body':'head'})}}return}
f.cooldown-=dt;f.facing=enemy.x>=f.x?1:-1;const dist=Math.abs(f.x-enemy.x);if(LB.game.training&&!LB.game.labAuto){f.state='idle';return}if(enemy.hp<=0){f.state='victory';return}
// React during the telegraph, with remembered attacks influencing the guard.
if(enemy.action&&!enemy.action.done&&enemy.action.time<enemy.action.impact&&f.cooldown<=0){let threat=enemy.action,read=.28+LB.abilityValue(f,'memory')+(f.memory[threat.target]||0)*.015;const dangerDist=enemy.weapon?290:190;if(dist<dangerDist&&Math.random()<dt*4*read){if(Math.random()<.35+LB.abilityValue(f,'dodge'))this.dodge(f,threat.target==='head'?'headSway':Math.random()<.7?'bodySway':'stepBack');else{f.state='block';f.guard=threat.target==='head'?'high':threat.target==='limb'?'low':'middle';f.blockSince=LB.game.time;f.cooldown=.28}return}}
if(LB.abilityValue(f,'distract')&&enemy.action&&!enemy.action.done&&Math.random()<dt*LB.abilityValue(f,'distract')){enemy.action=null;enemy.state='stunned';enemy.hitTimer=.5;LB.Particles.word(enemy.x,enemy.y-260,'POCKET SAND!');f.gainPopularity(6)}
const desired=(f.weapon?225:158)*(1-LB.abilityValue(f,'reach')*.25)+(f.appearance.style===1?5:f.appearance.style===2?-12:0),maxSeparation=LB.Camera.width/LB.Camera.height<.8?250:700;if(dist>desired+8){let move=Math.min(dist-desired,dt*(dist>320?285:LB.clamp((dist-desired)*6,45,215)));f.x+=f.facing*move;f.state=dist>320?'run':'walk';f.moveDir=1;f.stride+=move*Math.PI/(2*(f.state==='run'?36:24));return}if(dist<desired-30&&Math.random()<dt*1.5){const retreat=dt*125;f.x-=f.facing*retreat;f.state='walk';f.moveDir=-1;f.stride+=retreat*Math.PI/48;return}if(f.cooldown>0)return;if(f.stamina<16){f.state='block';f.cooldown=.38;f.gainPopularity(-.5);return}let roll=Math.random(),style=f.appearance.style;if(roll<.025+LB.abilityValue(f,'acrobat')*.3){this.start(f,'special');return}if(roll<.07+LB.abilityValue(f,'wrestle')*.3+(style===2?.1:0)&&dist<205){this.start(f,'grapple');return}if(f.weapon&&roll<.11){this.start(f,'throw');return}if(roll>.96){f.state='block';f.cooldown=.28;f.guard=LB.pick(['high','middle','low']);return}if(roll>.91){f.state='idle';f.cooldown=.28;f.frontFeint=true;enemy.gainPopularity(-1);return}const kind=f.weapon?'weapon':roll<.35+(style===1?.2:0)?'kick':roll>.75-LB.abilityValue(f,'combo')?'combo':'punch';this.start(f,kind)},
contact(f,enemy,act){const t=LB.game.time,p=LB.Animation.pose(f,t),kind=act.kind;let hit=LB.Rig.contact(f,t,kind),scale=f.appearance.height;const w=LB.weaponById(f.weapon);if(kind==='weapon'&&w){hit.x+=Math.sin(p.weaponAngle)*w.reach*f.facing*scale;hit.y-=Math.cos(p.weaponAngle)*w.reach*scale}const b=LB.bodySpecs[enemy.appearance.body],es=enemy.appearance.height,headY=enemy.y-(b.leg+b.torso+38)*es;let targetY=act.target==='head'?headY:act.target==='limb'?enemy.y-55*es:enemy.y-(b.leg+b.torso*.4)*es;let targetX=enemy.x;if(enemy.state==='headSway'&&act.target==='head')targetX-=enemy.facing*29;if(enemy.state==='bodySway')targetX-=enemy.facing*60;const dx=Math.abs(hit.x-targetX),dy=Math.abs(hit.y-targetY),radiusX=(act.target==='head'?42:b.w+10)*es+17,radiusY=act.target==='head'?53:act.target==='limb'?50:70;let connects=dx<radiusX&&dy<radiusY;if(['headSway','bodySway','stepBack'].includes(enemy.state)){const valid=enemy.state!=='headSway'||act.target==='head';if(valid){connects=false;LB.Particles.word(enemy.x,enemy.y-290,enemy.state==='headSway'?'WHIFF!':enemy.state==='bodySway'?'TOO SLOW!':'NOPE!','#d5e6b0');enemy.gainPopularity(7);enemy.cooldown=-.1;enemy.counterReady=true}}
if(!connects){f.gainPopularity(act.special?-10:-2);LB.Particles.burst(hit.x,hit.y,3,'#ede1b1','dust');if(act.special&&Math.random()<.14){f.state='knockdown';f.action=null;f.fallProgress=0;f.hitTimer=.95;f.gainPopularity(-15);LB.Particles.word(f.x,f.y-210,'NAILED IT. SORT OF.')}return}
let amount=f.damage*(kind==='kick'?1.25:act.special?1.65:kind==='combo'?.8:1);if(w&&kind==='weapon')amount=(f.damage*.5+w.damage*.65)*(1+LB.abilityValue(f,'weapon'));let blocked=enemy.state==='block'&&enemy.guard===(act.target==='head'?'high':act.target==='limb'?'low':'middle');if(blocked){const perfect=LB.game.time-(enemy.blockSince||0)<.3||Math.random()<.15+LB.abilityValue(enemy,'block');enemy.stats.blocks++;enemy.gainPopularity(perfect?12:4);enemy.stamina=Math.max(0,enemy.stamina-8);amount*=perfect?0:.24;LB.Particles.word(hit.x,hit.y-30,perfect?'PERFECT!':'CLANG!','#d6e2a2');LB.Audio.hit('metal');if(perfect){enemy.counterReady=true;enemy.cooldown=0}LB.Dialogue.say(enemy,'block');if(amount===0)return}
let critical=Math.random()<.09+LB.abilityValue(f,'luck');if(critical)amount*=1.6+LB.abilityValue(f,'critical');if(f.counterReady){amount*=1.3+LB.abilityValue(f,'counter');f.counterReady=false;LB.Particles.word(hit.x,hit.y-30,'RETURN TO SENDER!')}this.damage(f,enemy,amount,hit.x,hit.y,{kind,critical,special:act.special,blocked,rare:act.rare,finisher:act.finisher});f.memory[act.target]=(f.memory[act.target]||0)+1;enemy.memory[act.target]=(enemy.memory[act.target]||0)+1;},
damage(f,enemy,amount,x,y,meta={}){if(enemy.hp<=0||LB.game.finalHold)return;amount=Math.max(0,amount*(1-enemy.defense));if(LB.game.training&&!meta.rare)amount=Math.min(amount,Math.max(0,enemy.hp-1));if(meta.rare&&LB.game.training)amount=enemy.hp+1;if(enemy.hp-amount<=0&&!LB.game.training){if(LB.abilityValue(enemy,'lucky')&&Math.random()<LB.abilityValue(enemy,'lucky')&&!enemy.savedLuck){enemy.savedLuck=true;amount=enemy.hp-1;LB.Particles.word(enemy.x,enemy.y-280,'LUCKY BASTARD!')}else if(LB.abilityValue(enemy,'resurrection')&&!enemy.resurrectionSpent){enemy.resurrectionSpent=true;enemy.hp=enemy.maxHp*.25+amount;LB.Particles.word(enemy.x,enemy.y-280,'SECOND WIND!')}}enemy.hp=Math.max(0,enemy.hp-amount);f.damageDone+=amount;f.stats.hits++;if(meta.critical)f.stats.criticals++;f.combo++;f.comboTimer=2.5;f.gainPopularity(f.lastMove===meta.kind?-2:meta.special?18:meta.critical?12:5);f.lastMove=meta.kind;enemy.gainPopularity(-2);const knocked=(meta.critical||meta.special)&&Math.random()<.3*(1-LB.abilityValue(enemy,'knockdown'));const kb=(meta.special?75:meta.kind==='weapon'?(LB.weaponById(f.weapon)?.knockback||25)*.55:meta.critical?40:14)*(1+LB.abilityValue(f,'knockback'));enemy.vx=f.facing*kb;if(enemy.hp>0&&!meta.blocked&&!['grappled','lifted','carried','thrown'].includes(enemy.state)){enemy.action=null;enemy.state=knocked?'knockdown':'hurt';enemy.hitTimer=knocked?.8:.13;enemy.fallProgress=0;if(knocked)enemy.knockdowns++;enemy.x+=f.facing*(meta.special?16:7)}if(LB.settings.reducedGore)LB.Particles.burst(x,y,meta.critical?20:10,'#f6db7b');else{LB.Particles.blood(x,y,meta.critical?18:9,f.facing);LB.Particles.burst(x,y,4,'#efd277')}LB.Particles.burst(x,y,5,'#e9e7cd','sweat');LB.Particles.word(x,y-20,meta.critical?LB.pick(['BONE APPÉTIT!','FUCKING OUCH!','CRITICAL!']):LB.pick(['KRAK!','THWACK!','POW!','WHAM!']));LB.Camera.shake=meta.critical?7:3;LB.game.hitStop=meta.critical?.04:.018;LB.Audio.hit(meta.critical?'critical':meta.kind==='weapon'?'metal':'hit');LB.Crowd.react(meta.critical?'big':'hit');if(Math.random()<(meta.critical?.5:.07))LB.Dialogue.say(enemy,meta.critical?'critical':'hit',true);LB.Arena.breakNear(enemy.x,kb);if(enemy.hp<=0)this.lethal(f,enemy,meta)},
grapple(f,enemy,act,u,dt){if(u<.23){const d=enemy.x-f.x;f.x+=Math.sign(d)*Math.min(Math.abs(d)-65,dt*225);if(!act.grabbed&&u>.16){if(['stepBack','bodySway'].includes(enemy.state)&&!act.lab){act.done=true;act.duration=act.time+.35;f.gainPopularity(-9);return}act.grabbed=true;enemy.action=null;enemy.state='grappled';LB.Dialogue.say(enemy,'grabbed',true)}}else if(act.grabbed&&!act.done){const lift=LB.clamp((u-.23)/.2,0,1),motion=act.motion;enemy.state=lift<1?'lifted':'carried';enemy.x=f.x+f.facing*(motion==='airplane'?Math.cos(u*24)*65:55);enemy.y=LB.FLOOR-100*lift;enemy.physicsRotation=motion==='suplex'?-1.5*lift:motion==='javelin'||motion==='carry'?1.5*lift:motion==='airplane'?Math.sin(u*24)*1.2:.4*lift;enemy.facing=-f.facing;if(u>.42&&u<.65&&['carry','crowd','javelin'].includes(motion)){f.x+=f.facing*dt*95;enemy.x=f.x+f.facing*55}if(act.time>=act.impact){act.done=true;enemy.state='thrown';enemy.vx=f.facing*(motion==='javelin'?380:motion==='crowd'?290:motion==='slam'?45:180);enemy.vy=motion==='slam'?220:-200;enemy.spin=motion==='suplex'?-6:4;enemy.physicsRotation=0;LB.Particles.word(f.x,LB.FLOOR-290,(act.special?.name||motion).toUpperCase());this.damage(f,enemy,f.damage*1.9*(1+LB.abilityValue(f,'wrestle')),enemy.x,enemy.y-110,{kind:'grapple',special:true,critical:true,rare:act.rare,finisher:act.finisher});f.gainPopularity(18)}}},
lethal(winner,loser,meta){
 const pose=LB.Animation.pose(loser,LB.game.time);
 const first=LB.Finishers.count===0;
 const cinematic=meta.rare||first||Math.random()<Math.min(.95,.72+LB.abilityValue(winner,'finisher'));
 const outcome=cinematic?LB.Finishers.perform(winner,loser,meta.finisher,pose):null;
 loser.action=null;loser.hitTimer=10;loser.fallProgress=0;if(loser.state!=='thrown')loser.state='defeat';
 winner.action=null;winner.state='victory';
 const label=outcome?LB.Finishers.labels[outcome]:'KNOCKED THE FUCK OUT.';
 LB.game.finalHold={elapsed:0,duration:4,winner,loser,label,finisher:outcome};
 LB.game.hitStop=.1;LB.Camera.shake=10;LB.Dialogue.say(winner,'win',true);LB.UI.announce(label,4);LB.Audio.hit('critical');LB.Audio.win();LB.Crowd.react('big');
}
};
