'use strict';
(()=>{const decks={
intro:['Who the fuck booked this?','I parked in a fire lane for this.','My lawyer said absolutely not.','You look like a refund dispute.','I was promised free beer.','Let’s make some poor decisions.','This counts as cardio, right?'],
banter:['Your whole vibe owes me money.','I’ve had tougher frozen dinners.','This is why we can’t have shit.','I am catastrophically underqualified.','Your stance has a cancellation fee.','My back is making dial-up noises.','You smell like a bad investment.'],
insult:['Discount-bin menace.','You sentient parking ticket.','You absolute shit casserole.','Budget-ass final boss.','You walking inconvenience.','Your confidence is a clerical error.','Fucking clearance-rack villain.'],
reply:['Put that in a fucking email.','Cool story. Hit the unsubscribe.','That’s rich coming from you.','I charge extra for emotional damage.','I’ve ignored better people.','Talk shit, meet deductible.','Your feedback has been deleted.'],
win:['Keep the change, dipshit.','That was legally almost exercise.','I accept cash and apologies.','Fuck yes. Still inexplicably alive.','Tell your manager I won.','Another satisfied customer.','I’m billing you for these pants.'],
beg:['Wait! I have an expired coupon!','Not the face! It’s on my ID!','I have six unread work emails!','Okay, fucking time out!','Can we settle this in installments?','My therapist will hear about this!','I am not built for consequences!'],
dodge:['Missed me, shitbird.','Wrong address, asshole.','Nice swing. Try having eyes.','That punch had airplane Wi-Fi.','Return to fucking sender.','You hit my emotional support air.','Oops. Still pretty.'],
block:['Nope. Union rules.','Blocked. Like your number.','My elbows have tenure.','That all you got, fuckface?','Access fucking denied.','You’re on the wrong subscription.','Put some rent money into it.'],
grapple:['Time for the forklift treatment.','We’re doing trust falls, asshole.','Up you fucking go.','Your feet are getting evicted.','This is a hostile takeover.','Special delivery. No signature.','Let me rearrange your schedule.'],
grabbed:['Put me down, you weird shit!','I did not consent to flying!','My fucking lumbar region!','This is not a networking event!','I’m gonna puke on your shoes!','I weigh more emotionally!','I have a fragile sticker!'],
hit:['Ow, you petty bastard.','That was my good organ!','Well, shit on a receipt.','Fucking hell, that stings.','I felt that in my credit score.','Those are rented teeth!','Okay, now it’s mildly personal.'],
critical:['Holy shit, my skeleton!','That punch needs a fucking permit.','My soul just clocked out.','You knocked my tax bracket loose.','I can taste next Thursday.','Fuck! That had punctuation!','My ancestors felt that one.']};
const tags=['',' Seriously.',' You heard me.',' Put it on my tab.'];LB.dialogue={};for(const [k,lines]of Object.entries(decks))LB.dialogue[k]=lines.flatMap(s=>tags.map(t=>s+t));
LB.crowdLines=['KICK HIS CREDIT SCORE!','I PAID NOTHING AND I WANT A REFUND!','SOMEBODY FILM THIS SHIT!','THAT’S MY FUCKING COOLER!','DO A FLIP, YOU COWARD!','STOP HITTING THE FURNITURE!','MY LAWYER LOVES THIS!','THROW THE WHOLE BASTARD!','BOOO! EMBARRASSING!','I KNOW THAT IDIOT FROM WORK!','THIS BEATS THE POTLUCK!','THAT TOOTH OWES ME MONEY!','NO REFUNDS! NO WITNESSES!','HIT HIM WITH THE ECONOMY!','FIGHT LIKE RENT IS DUE!','IS THIS COVERED BY INSURANCE?','I’M CANCELING MY GYM MEMBERSHIP!','THIS IS FUCKING ART!','THE HOA WILL HEAR ABOUT THIS!','TWO STARS! GREAT PARKING!','TAKE IT OUTSIDE! WAIT—','MY KID DRAWS BETTER GUARDS!','I’M LIVE STREAMING THE LAWSUIT!','SOMEONE CHECK THE DEPOSIT!','YES! MAKE IT A PROBLEM!','WHAT A BEAUTIFUL DISASTER!','I BET MY LUNCH ON YOU!','LESS TALK! MORE BAD CHOICES!','THAT’S A LOAD-BEARING MORON!','GET UP! THE BUFFET CLOSES SOON!'];
LB.Dialogue={decks:{},next:10,crowd:null,take(k){if(!this.decks[k]?.length)this.decks[k]=LB.shuffle(LB.dialogue[k]||LB.crowdLines);return this.decks[k].pop()},say(f,k,force=false){if(!force&&Math.random()>.3)return;if(f.speech&&f.speech.until>LB.game.time)return;f.speech={text:this.take(k),until:LB.game.time+3.4}},update(dt){this.next-=dt;if(this.next<0){this.next=LB.rand(9,16);this.say(LB.pick(LB.game.fighters),'banter',true)}if(this.crowd&&this.crowd.until<LB.game.time)this.crowd=null},shout(){if(!this.crowd)this.crowd={text:this.take('crowd'),until:LB.game.time+3}}};
})();
