'use strict';
LB.Particles={items:[],words:[],stains:[],
 burst(x,y,n,color='#edcc64',kind='spark'){n=Math.min(n,LB.settings.quality==='performance'?24:40);for(let i=0;i<n;i++){if(this.items.length>=180)this.items.shift();this.items.push({x,y,vx:LB.rand(-230,230),vy:LB.rand(-250,35),life:LB.rand(.3,.85),color,size:LB.rand(2,6),angle:Math.random()*6,spin:LB.rand(-12,12),kind})}},
 blood(x,y,n=16,direction=1){if(LB.settings.reducedGore)return;for(let i=0;i<Math.min(n,28);i++){if(this.items.length>=180)this.items.shift();this.items.push({x,y,vx:direction*LB.rand(40,190)+LB.rand(-100,100),vy:LB.rand(-240,35),life:LB.rand(1.1,1.8),color:LB.pick(['#a62432','#ba2934','#811d2b']),size:LB.rand(2.5,7),angle:0,spin:LB.rand(-4,4),kind:'blood'})}},
 stain(x,y,size){if(LB.settings.reducedGore)return;const nearby=this.stains.find(p=>Math.abs(p.x-x)<20&&Math.abs(p.y-y)<10);if(nearby){nearby.size=Math.min(40,nearby.size+size*.15);return}if(this.stains.length>=36)this.stains.shift();this.stains.push({x,y:y+LB.rand(0,5),size:LB.clamp(size,4,40)})},
 word(x,y,text,color='#f9d250'){if(this.words.length>7)this.words.shift();this.words.push({x,y,text,color,life:.7})},
 update(dt){for(let i=this.items.length-1;i>=0;i--){const p=this.items[i];p.life-=dt;p.vy+=(p.kind==='blood'?700:460)*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.angle+=p.spin*dt;if(p.y>LB.FLOOR){p.y=LB.FLOOR;if(p.kind==='blood'){this.stain(p.x,p.y,p.size*1.4);p.life=0}else{p.vy*=-.35;p.vx*=.7}}if(p.life<=0)this.items.splice(i,1)}for(let i=this.words.length-1;i>=0;i--){this.words[i].life-=dt;this.words[i].y-=35*dt;if(this.words[i].life<=0)this.words.splice(i,1)}},
 drawGround(c){if(LB.settings.reducedGore)return;for(const p of this.stains){LB.ellipse(c,p.x,p.y,p.size,p.size*.18,'#852133bb');LB.ellipse(c,p.x+p.size*.8,p.y+4,p.size*.25,2,'#a32d36bb');LB.ellipse(c,p.x-p.size*.65,p.y-3,3,1.6,'#9e2834bb')}},
 draw(c){for(const p of this.items){if(LB.settings.reducedGore&&p.kind==='blood')continue;c.save();c.globalAlpha=Math.min(1,p.life*2);c.translate(p.x,p.y);c.rotate(p.kind==='blood'?Math.atan2(p.vy,p.vx)+Math.PI/2:p.angle);if(p.kind==='spark')LB.path(c,`M0 ${-p.size*2} L${p.size*.6} ${-p.size*.5} ${p.size*2} 0 ${p.size*.6} ${p.size*.5} 0 ${p.size*2} ${-p.size*.5} ${p.size*.5} ${-p.size*2} 0 ${-p.size*.6} ${-p.size*.5}Z`,p.color,LB.ink,1);else if(p.kind==='blood')LB.path(c,`M0 ${-p.size*2} Q${-p.size*1.2} ${p.size} 0 ${p.size} Q${p.size*1.3} ${p.size} 0 ${-p.size*2}Z`,p.color,null);else if(p.kind==='dust')LB.ellipse(c,0,0,p.size*2,p.size,p.color);else LB.path(c,`M-${p.size} -2 L${p.size} -4 ${p.size*.5} 4 -2 2Z`,p.color,LB.ink,1);c.restore()}for(const p of this.words){c.save();c.translate(p.x,p.y);c.rotate(-.12);c.globalAlpha=Math.min(1,p.life*3);c.textAlign='center';c.font='900 30px Impact';c.lineWidth=5;c.strokeStyle=LB.ink;c.strokeText(p.text,0,0);c.fillStyle=p.color;c.fillText(p.text,0,0);c.restore()}}
};
