'use strict';
(()=>{const qs=[];function add(category,prompt,answer,wrong,explanation){const s=String(answer);let choices=[s,...wrong.map(String).filter(v=>v!==s)];choices=[...new Set(choices)];let n=1;while(choices.length<4){const v=String(Number(answer)+n++*3);if(!choices.includes(v))choices.push(v)}qs.push({id:qs.length,category,prompt,answer:s,choices:choices.slice(0,4),explanation})}const num=(cat,p,a,why)=>add(cat,p,a,[a+1,a-1,a+3],why);
// Basic arithmetic only: small sums, times tables, exact division and everyday counting.
for(let i=0;i<100;i++){
 const a=i%10+1,b=Math.floor(i/10)+1;
 num('Addition',`What is ${a} + ${b+10}?`,a+b+10,'Add the two numbers. Death forgot to make this one difficult.');
 num('Subtraction',`What is ${a+10} − ${b}?`,a+10-b,'Take the second number away from the first. Keep your fingers attached.');
 num('Multiplication',`What is ${a} × ${b}?`,a*b,'A basic times-table question. Finally, school pays the medical bill.');
 num('Division',`What is ${a*b} ÷ ${a}?`,b,'Split it into equal groups. No fractions, no bullshit.');
 num('Counting',`What whole number comes immediately after ${i+1}?`,i+2,'Just add one. Death is having an off day.');
 num('Money',`You pay $${b+10} for a $${a} snack. How many dollars should you get back?`,b+10-a,'Subtract the price from what you paid. The cashier is not a final boss.');
 num('Doubles',`What is double ${i+1}?`,2*(i+1),'Add the number to itself. Two bad ideas for the price of one.');
 num('Halves',`What is half of ${2*(i+1)}?`,i+1,'Split the number into two equal parts. Unlike your last relationship.');
}
const capitals=[['Kazakhstan','Astana','Almaty','Bishkek','Tashkent'],['Kyrgyzstan','Bishkek','Dushanbe','Astana','Ashgabat'],['Tajikistan','Dushanbe','Samarkand','Baku','Tbilisi'],['Eritrea','Asmara','Addis Ababa','Djibouti','Khartoum'],['Bhutan','Thimphu','Paro','Kathmandu','Dhaka'],['Palau','Ngerulmud','Koror','Majuro','Funafuti'],['Tuvalu','Funafuti','Suva','Apia','Nukuʻalofa'],['Kiribati','South Tarawa','Honiara','Port Vila','Palikir'],['Micronesia','Palikir','Majuro','Ngerulmud','Apia'],['Marshall Islands','Majuro','Palikir','Suva','Tarawa'],['Comoros','Moroni','Mamoudzou','Victoria','Port Louis'],['Seychelles','Victoria','Moroni','Port Louis','Antananarivo'],['Mauritius','Port Louis','Victoria','Moroni','Roseau'],['Suriname','Paramaribo','Georgetown','Cayenne','Belmopan'],['Belize','Belmopan','Belize City','Tegucigalpa','Managua'],['Dominica','Roseau','Castries','Bridgetown','St. George’s'],['Saint Lucia','Castries','Roseau','Kingstown','Basseterre'],['Saint Kitts and Nevis','Basseterre','Kingstown','Castries','St. John’s'],['Saint Vincent and the Grenadines','Kingstown','Georgetown','Roseau','Basseterre'],['Grenada','St. George’s','Kingstown','Castries','St. John’s'],['Burkina Faso','Ouagadougou','Bamako','Niamey','Lomé'],['Benin (official capital)','Porto-Novo','Cotonou','Lomé','Accra'],['Côte d’Ivoire (official capital)','Yamoussoukro','Abidjan','Bouaké','Monrovia'],['Malawi','Lilongwe','Blantyre','Lusaka','Harare'],['Lesotho','Maseru','Mbabane','Gaborone','Pretoria']];for(const [country,answer,...wrong]of capitals)add('Capitals',`What is the capital of ${country}?`,answer,wrong,`${answer}. Geography has no sympathy for your situation.`);
const elements=[['Sc',21],['Ti',22],['V',23],['Cr',24],['Mn',25],['Fe',26],['Co',27],['Ni',28],['Cu',29],['Zn',30],['Ga',31],['Ge',32],['As',33],['Se',34],['Br',35],['Kr',36],['Rb',37],['Sr',38],['Y',39],['Zr',40],['Nb',41],['Mo',42],['Tc',43],['Ru',44],['Rh',45]];for(const [symbol,z]of elements)num('Chemistry',`How many protons are in the nucleus of an atom with chemical symbol ${symbol}?`,z,`The atomic number of ${symbol} is ${z}. The protons have formed a very small union.`);
for(let i=0;i<25;i++){
const files=i+1,added=i%5+1;num('Computing',`A folder has ${files} files. You add ${added} more. How many files are there now?`,files+added,'Add the files together. No computer science degree required.');
const metres=i+1;num('Scientific units',`There are 100 centimetres in one metre. How many centimetres are in ${metres} metres?`,metres*100,'Multiply by 100. The question even gave you the conversion, you lucky bastard.');
const books=i+5;num('Logic',`You have ${books} books and give away 2. How many books do you have left?`,books-2,'Subtract two. No hidden boxes, secret rules or philosophical nonsense.');
const words=['BANANA','BALLOON','MISSISSIPPI','COMMITTEE','TATTOO','PEPPER','LEVEL','KAYAK','MAMMAL','ASSESS','SUCCESS','COCOA','ROTOR','TOMATO','POTATO','DEED','NOON','CIVIC','REFER','TENET','TOOT','DAD','MOM','POP','SASS'];const word=words[i];num('Wordplay',`How many letters are in the word ${word}?`,word.length,'Count each letter once, including repeats. Spelling finally saves your ass.');
const candles=i+5;num('Everyday counting',`There are ${candles} unlit candles. You light 3. How many are still unlit?`,candles-3,'Take away the three you lit. No sneaky burning-away trick this time.');
}
const animals=[['Which living group contains the closest relatives of crocodilians?','Birds','Lizards','Turtles','Mammals'],['Which animal has three hearts?','Octopus','Nautilus','Lobster','Sea cucumber'],['Which mammal lays eggs?','Echidna','Pangolin','Armadillo','Aardvark'],['What is a tuatara?','A reptile in Rhynchocephalia','A lizard in Squamata','An amphibian','A small marsupial'],['Which animal has blue blood due to hemocyanin?','Horseshoe crab','Atlantic cod','African lungfish','Lamprey'],['A narwhal’s long tusk is primarily what?','An enlarged tooth','A horn of keratin','A bony antler','A modified rib'],['Which has the most neck vertebrae among these?','Swan','Giraffe','Human','Horse'],['Which is a monotreme?','Platypus','Koala','Wombat','Quokka'],['What is an axolotl’s class?','Amphibia','Reptilia','Actinopterygii','Mammalia'],['Which is a true fly with one pair of functional wings?','Mosquito','Dragonfly','Mayfly','Caddisfly'],['Which is an arachnid?','Tick','Flea','Louse','Silverfish'],['Which is a cartilaginous fish?','Manta ray','Moray eel','Seahorse','Sturgeon'],['Which is a marsupial?','Virginia opossum','Raccoon','Skunk','Hedgehog'],['Which bird is native to Antarctica?','Emperor penguin','Atlantic puffin','Great auk','Kiwi'],['What are shark dermal denticles structurally similar to?','Teeth','Feathers','Hair','Nails'],['Which animal produces a cube-like dropping?','Wombat','Koala','Capybara','Beaver'],['What is the largest living species of lizard?','Komodo dragon','Nile monitor','Green iguana','Gila monster'],['Which mammal truly flies under its own power?','Bat','Flying squirrel','Colugo','Sugar glider'],['A starfish belongs to which phylum?','Echinodermata','Mollusca','Cnidaria','Arthropoda'],['A jellyfish belongs to which phylum?','Cnidaria','Annelida','Mollusca','Chordata'],['Which animal uses nematocysts?','Sea anemone','Sea urchin','Limpet','Horseshoe crab'],['Which has an open circulatory system?','Grasshopper','Earthworm','Squid','Trout'],['Which has a closed circulatory system?','Squid','Snail','Crab','Butterfly'],['What is the principal structural protein in spider silk?','Spidroin','Keratin','Collagen','Elastin'],['Which is a flightless parrot?','Kakapo','Kea','Cassowary','Takahe']];for(const [p,a,...w]of animals)add('Animals',p,a,w,`${a}. Nature is weird, but your opponent is weirder.`);
if(qs.length!==1000)throw Error('Trivia count must equal 1000');LB.trivia=qs;
LB.Trivia={used:new Set(),choose(){if(this.used.size===1000)this.used.clear();let q;do{q=LB.pick(LB.trivia)}while(this.used.has(q.id));this.used.add(q.id);return {...q,choices:LB.shuffle(q.choices)}}};
})();
