'use strict';
(()=>{const qs=[];function add(category,prompt,answer,wrong,explanation){const s=String(answer);let choices=[s,...wrong.map(String).filter(v=>v!==s)];choices=[...new Set(choices)];let n=1;while(choices.length<4){const v=String(Number(answer)+n++*3);if(!choices.includes(v))choices.push(v)}qs.push({id:qs.length,category,prompt,answer:s,choices:choices.slice(0,4),explanation})}const num=(cat,p,a,why)=>add(cat,p,a,[a+1,a-1,a+3],why);const choose=(n,k)=>{let v=1;for(let i=1;i<=k;i++)v=v*(n-i+1)/i;return Math.round(v)};
for(let i=0;i<100;i++){
const a=i+13,b=i%9+3,c=i%7+2;num('Arithmetic traps',`Evaluate ${a} − ${b} × ${c} + ${b*c+7}.`,a+7,'Multiplication first. Your calculator did not need a fistfight.');
const p=i+11;num('Percentages',`A price rises by ${p}% then falls by ${p}%. What percentage of the original price remains?`,Math.round((100-p*p/100)*100)/100,`Multiply (1 + ${p}/100)(1 − ${p}/100). Percentages are petty like that.`);
let base=i+7,exp=i%5+4,m=i%17+7,res=1;for(let e=0;e<exp;e++)res=res*base%m;num('Modular arithmetic',`What is the least nonnegative remainder of ${base}^${exp} divided by ${m}?`,res,'Reduce after every multiplication. Enormous numbers hate this one boring trick.');
const val=113+i*7,radix=3+i%7;add('Number bases',`Convert ${val.toString(radix).toUpperCase()} (base ${radix}) to decimal.`,val,[val-radix,val+radix,val+radix*radix],'Each digit is weighted by a power of its base. Counting, with extra paperwork.');
const n=i+4;num('Sequences',`For aₙ = n³ − 2n, what is a${n}?`,n*n*n-2*n,'Cube the index, then subtract twice the index. No numerology required.');
const x=i+9,y=i%13+5;num('Geometry',`A right triangle has perpendicular legs ${x} and ${y}. What is the square of its hypotenuse?`,x*x+y*y,'Pythagoras bills by the square. Add the squares of both legs.');
const total=i+8,k=i%3+2;num('Combinatorics',`How many unordered groups of ${k} can be selected from ${total} distinct contestants?`,choose(total,k),'Use n! / (k!(n−k)!). Order is irrelevant, just like the referee.');
const hr=i%12,min=Math.floor(i/12)*7+i%7;let angle=Math.abs(30*hr-5.5*min);angle=Math.min(angle,360-angle);num('Clock angles',`What is the smaller angle in degrees between clock hands at ${hr||12}:${String(min).padStart(2,'0')}?`,angle,'The hour hand moves too: 30h − 5.5m. Time remains a bastard.');
}
const capitals=[['Kazakhstan','Astana','Almaty','Bishkek','Tashkent'],['Kyrgyzstan','Bishkek','Dushanbe','Astana','Ashgabat'],['Tajikistan','Dushanbe','Samarkand','Baku','Tbilisi'],['Eritrea','Asmara','Addis Ababa','Djibouti','Khartoum'],['Bhutan','Thimphu','Paro','Kathmandu','Dhaka'],['Palau','Ngerulmud','Koror','Majuro','Funafuti'],['Tuvalu','Funafuti','Suva','Apia','Nukuʻalofa'],['Kiribati','South Tarawa','Honiara','Port Vila','Palikir'],['Micronesia','Palikir','Majuro','Ngerulmud','Apia'],['Marshall Islands','Majuro','Palikir','Suva','Tarawa'],['Comoros','Moroni','Mamoudzou','Victoria','Port Louis'],['Seychelles','Victoria','Moroni','Port Louis','Antananarivo'],['Mauritius','Port Louis','Victoria','Moroni','Roseau'],['Suriname','Paramaribo','Georgetown','Cayenne','Belmopan'],['Belize','Belmopan','Belize City','Tegucigalpa','Managua'],['Dominica','Roseau','Castries','Bridgetown','St. George’s'],['Saint Lucia','Castries','Roseau','Kingstown','Basseterre'],['Saint Kitts and Nevis','Basseterre','Kingstown','Castries','St. John’s'],['Saint Vincent and the Grenadines','Kingstown','Georgetown','Roseau','Basseterre'],['Grenada','St. George’s','Kingstown','Castries','St. John’s'],['Burkina Faso','Ouagadougou','Bamako','Niamey','Lomé'],['Benin (official capital)','Porto-Novo','Cotonou','Lomé','Accra'],['Côte d’Ivoire (official capital)','Yamoussoukro','Abidjan','Bouaké','Monrovia'],['Malawi','Lilongwe','Blantyre','Lusaka','Harare'],['Lesotho','Maseru','Mbabane','Gaborone','Pretoria']];for(const [country,answer,...wrong]of capitals)add('Capitals',`What is the capital of ${country}?`,answer,wrong,`${answer}. Geography has no sympathy for your situation.`);
const elements=[['Sc',21],['Ti',22],['V',23],['Cr',24],['Mn',25],['Fe',26],['Co',27],['Ni',28],['Cu',29],['Zn',30],['Ga',31],['Ge',32],['As',33],['Se',34],['Br',35],['Kr',36],['Rb',37],['Sr',38],['Y',39],['Zr',40],['Nb',41],['Mo',42],['Tc',43],['Ru',44],['Rh',45]];for(const [symbol,z]of elements)num('Chemistry',`How many protons are in the nucleus of an atom with chemical symbol ${symbol}?`,z,`The atomic number of ${symbol} is ${z}. The protons have formed a very small union.`);
for(let i=0;i<25;i++){
const bits=i+9;num('Computing',`How many distinct unsigned values can exactly ${bits} bits represent?`,2**bits,'There are two possibilities per bit: 2ⁿ. Your computer is just very organized indecision.');
const val=i+17;num('Scientific units',`Convert ${val} kilopascals into newtons per square metre.`,val*1000,'One pascal is one newton per square metre; kilo means 1,000. Pressure, now with paperwork.');
const n=i+5;num('Logic',`There are ${n} sealed boxes. Exactly one contains a key. A perfect test checks one box. In the worst case, how many tests identify the key’s box, without needing to open it?`,n-1,'After n−1 empty boxes, the remaining box is forced. The last box cannot plead ignorance.');
const words=['BANANA','BALLOON','MISSISSIPPI','COMMITTEE','TATTOO','PEPPER','LEVEL','KAYAK','MAMMAL','ASSESS','SUCCESS','COCOA','ROTOR','TOMATO','POTATO','DEED','NOON','CIVIC','REFER','TENET','TOOT','DAD','MOM','POP','SASS'];const word=words[i],counts={};for(const ch of word)counts[ch]=(counts[ch]||0)+1;const fact=n=>n<2?1:n*fact(n-1);let ans=fact(word.length);for(const count of Object.values(counts))ans/=fact(count);num('Wordplay',`How many distinct letter arrangements (including nonsense) can be made from ${word}?`,ans,'Divide the factorial of the length by factorials of repeated-letter counts. Nonsense is finally useful.');
const candles=i+12,out=i%5+2;num('Difficult trick questions',`${candles} identical candles are burning. You extinguish ${out}; all the others burn completely away. How many candles remain at the end?`,out,'Only the extinguished candles survive. Congratulations on saving the least productive employees.');
}
const animals=[['Which living group contains the closest relatives of crocodilians?','Birds','Lizards','Turtles','Mammals'],['Which animal has three hearts?','Octopus','Nautilus','Lobster','Sea cucumber'],['Which mammal lays eggs?','Echidna','Pangolin','Armadillo','Aardvark'],['What is a tuatara?','A reptile in Rhynchocephalia','A lizard in Squamata','An amphibian','A small marsupial'],['Which animal has blue blood due to hemocyanin?','Horseshoe crab','Atlantic cod','African lungfish','Lamprey'],['A narwhal’s long tusk is primarily what?','An enlarged tooth','A horn of keratin','A bony antler','A modified rib'],['Which has the most neck vertebrae among these?','Swan','Giraffe','Human','Horse'],['Which is a monotreme?','Platypus','Koala','Wombat','Quokka'],['What is an axolotl’s class?','Amphibia','Reptilia','Actinopterygii','Mammalia'],['Which is a true fly with one pair of functional wings?','Mosquito','Dragonfly','Mayfly','Caddisfly'],['Which is an arachnid?','Tick','Flea','Louse','Silverfish'],['Which is a cartilaginous fish?','Manta ray','Moray eel','Seahorse','Sturgeon'],['Which is a marsupial?','Virginia opossum','Raccoon','Skunk','Hedgehog'],['Which bird is native to Antarctica?','Emperor penguin','Atlantic puffin','Great auk','Kiwi'],['What are shark dermal denticles structurally similar to?','Teeth','Feathers','Hair','Nails'],['Which animal produces a cube-like dropping?','Wombat','Koala','Capybara','Beaver'],['What is the largest living species of lizard?','Komodo dragon','Nile monitor','Green iguana','Gila monster'],['Which mammal truly flies under its own power?','Bat','Flying squirrel','Colugo','Sugar glider'],['A starfish belongs to which phylum?','Echinodermata','Mollusca','Cnidaria','Arthropoda'],['A jellyfish belongs to which phylum?','Cnidaria','Annelida','Mollusca','Chordata'],['Which animal uses nematocysts?','Sea anemone','Sea urchin','Limpet','Horseshoe crab'],['Which has an open circulatory system?','Grasshopper','Earthworm','Squid','Trout'],['Which has a closed circulatory system?','Squid','Snail','Crab','Butterfly'],['What is the principal structural protein in spider silk?','Spidroin','Keratin','Collagen','Elastin'],['Which is a flightless parrot?','Kakapo','Kea','Cassowary','Takahe']];for(const [p,a,...w]of animals)add('Animals',p,a,w,`${a}. Nature is weird, but your opponent is weirder.`);
if(qs.length!==1000)throw Error('Trivia count must equal 1000');LB.trivia=qs;
LB.Trivia={used:new Set(),choose(){if(this.used.size===1000)this.used.clear();let q;do{q=LB.pick(LB.trivia)}while(this.used.has(q.id));this.used.add(q.id);return {...q,choices:LB.shuffle(q.choices)}}};
})();
